export { default as Nav } from "./Nav/Nav";
export { default as ContactBtn } from "./ContactBtn/ContactBtn";
export { default as CTABtn } from "./CTABtn/CTABtn";
export { default as Intro } from "./IntroText/Intro";
export { default as PageHeader } from "./PageHeader/PageHeader";
export { default as SkillsIntro } from "./SkillsIntro/SkillsIntro";
export { default as SectionTitle } from "./SectionTitle/SectionTitle";
export { default as WorkCard } from "./WorkCard/WorkCard";
export { default as SkillsBox } from "./SkillsBox/SkillsBox";
export { default as AboutText } from "./AboutText/AboutText";
// export { default as Cursor } from "./Cursor/Cursor";
